### ISSUE TITLE
Add option to download network

### ISSUE THREAD

**Issue by coleslaw481** [idekerlab/NBGWAS-Frontend#2]
This ticket is originally from: https://github.com/idekerlab/nbgwas_rest/issues/14

Add a link to let the user download the NDEx network used in the analysis.

**Comment by BrettJSettle** [comment]
I thought we were going to add a link to VIEW the analysis results on NDEx (which would have it's own download button). Why would I link them to the network they passed in?

**Comment by coleslaw481** [comment]
Good question. Let me check with these guys.
